version: 1.26.2

services: 
    Elasticsearch :
        image: elasticsearch:8.7.0
        container_name: elasticsearch
        restart: always
        environment: 
            discovery.type: single-node

        ports: 
        - '9200:9200'
        - '9300:9300'





